
version: "2"

services:

  gateway:
    build:
      context: gateway
    ports:
      - "5000:5000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: rabbit
      RABBIT_PORT: "5672"

    depends_on:
      - waitforrabbit


  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./data:/data


  rabbit:
    image: rabbitmq:3.7-management
    ports:
        - "15673:15672"
        - "5672:5672"

    restart: always


  catcher:
    build:
      context: catcher

    depends_on:
      - waitforrabbit
      - redis

    environment:
        REDIS_HOST: redis
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"


  controller:
    build:
      context: controller

    depends_on:
      - waitforrabbit
      - redis

    environment:
        REDIS_HOST: redis
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"


  crawler:
    build:
      context: crawler
    depends_on:
      - waitforrabbit
      - redis

    environment:
        REDIS_HOST: redis
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"


  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbit

    command: rabbit:5672