
version: "2"

services:
  
  rabbit:
    image: rabbitmq:3.7-management
    ports:
        - "15673:15672"
        - "5672:5672"
    restart: always

  server:
    build:
      context: server
    depends_on:
      - waitforrabbit
    ports:
      - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"

  can:
    build:
      context: can
    depends_on:
      - waitforrabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"

  usa:
    build:
      context: usa
    depends_on:
      - waitforrabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"

  bra:
    build:
      context: bra
    depends_on:
      - waitforrabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: rabbit
        RABBIT_PORT: "5672"

  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbit
    command: rabbit:5672